package com.example.minesweeper.repository;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import com.example.minesweeper.model.Game;
import com.example.minesweeper.repository.exception.GameLoadingException;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.node.ArrayNode;
import org.springframework.data.annotation.Id;

@DynamoDBTable(tableName = "MineSweeperGame")
public class SavedGame {

    @Id
    private SavedGameId savedGameId;

    private String player;

    private String id;

    private int rows;

    private int columns;

    private String cellMines;

    private String cellState;

    public SavedGame() {
    }

    public SavedGame(Game game) {
        player = game.getPlayer();
        id = game.getId();
        savedGameId = new SavedGameId(player, id);
        rows = game.getRows();
        columns = game.getColumns();
        try {
            ObjectMapper objectMapper = new ObjectMapper();
            cellMines = objectMapper.writeValueAsString(game.getCellMines());
            cellState = objectMapper.writeValueAsString(game.getCellState());
        }
        catch(JsonProcessingException e) {
            e.printStackTrace();
        }
    }

    @DynamoDBHashKey(attributeName = "player")
    public String getPlayer() {
        return player;
    }

    public void setPlayer(String player) {
        this.player = player;
    }

    @DynamoDBRangeKey(attributeName = "id")
    @DynamoDBAutoGeneratedKey
    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    @DynamoDBAttribute(attributeName = "rows")
    public int getRows() {
        return rows;
    }

    public void setRows(int rows) {
        this.rows = rows;
    }

    @DynamoDBAttribute(attributeName = "columns")
    public int getColumns() {
        return columns;
    }

    public void setColumns(int columns) {
        this.columns = columns;
    }

    @DynamoDBAttribute(attributeName = "cellMines")
    public String getCellMines() {
        return cellMines;
    }

    public void setCellMines(String cellMines) {
        this.cellMines = cellMines;
    }

    @DynamoDBAttribute(attributeName = "cellState")
    public String getCellState() {
        return cellState;
    }

    public void setCellState(String cellState) {
        this.cellState = cellState;
    }

    public Game toGame() {
        Game game = new Game(player, id, rows, columns);
        String[][] newCellMines = new String[rows][columns];
        String[][] newCellState = new String[rows][columns];
        ObjectMapper objectMapper = new ObjectMapper();
        try {
            ArrayNode minesMatrixNode = (ArrayNode)objectMapper.readTree(cellMines);
            ArrayNode stateMatrixNode = (ArrayNode)objectMapper.readTree(cellState);
            for(int i = 0; i < minesMatrixNode.size(); i++) {
                ArrayNode minesRowNode = (ArrayNode)minesMatrixNode.get(i);
                ArrayNode stateRowNode = (ArrayNode)stateMatrixNode.get(i);
                for(int j = 0; j < minesRowNode.size(); j++) {
                    newCellMines[i][j] = minesRowNode.get(j).textValue();
                    newCellState[i][j] = stateRowNode.get(j).textValue();
                }
            }
            game.setCellMines(newCellMines);
            game.setCellState(newCellState);
            return game;
        } catch (JsonProcessingException e) {
            throw new GameLoadingException("Could not parse the game loader from the database");
        }
    }
}
